# Generated by Django 3.1.4 on 2020-12-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bidmodel_categories_closedlistings_comments_listings_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
    ]
